title: h/acc
description: hyperstitional accelerationism
baseurl: "" # Leave empty if using a custom domain
url: "https://sovietonion1608.github.io" # Replace with your GitHub Pages URL

# Pagination and Markdown Settings
paginate: 10
markdown: kramdown
theme: minima # You can customize this theme further

# Plugins (to enable search functionality)
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude unnecessary files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
